layout: sidebar
style: dark #light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 6
  exclude:
    archived: false
    forks: true
    projects:
    #  - TravlendarPlus
    #  - Hybrid-Recommender
    #  - Sales-Prediction
    #  - ML-miniproject
    #  - Object-Oriented-Class-Projects
    #  - Image-Deblurring

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: gmenchetti
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: guglielmo-menchetti
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username
  leetcode: gmenchetti

topics:
  - name: Theses and Publications
    web_url: publications
    image_url: images/Publication.png

  - name: Slides and Notes
    web_url: slidesnotes
    image_url: images/Presentation.png

  #- name: School 
  #- name: CSS
  #  web_url: https://github.com/topics/css
  #  image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  #- name: Web design

  #- name: Sass
  #  web_url: https://github.com/topics/sass
  #  image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
